# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
types = TeaType.create([{name: 'Black', title: 'blacktitle.png', image: 'black.png', repTea:'Lapsang souchong, Keemun tea, Assam tea, Nilgiri tea, Rize Tea, Dian Hong tea'},
{name: 'Oolong', title: 'oolongtitle.png', image: 'oolong.png', repTea: 'Pouchong, Tieguanyin, Rou Gui, Darjeeling tea, Dong Ding tea, Shui Hsien tea'},
{name: 'White', title: 'whitetitle.png',  image: 'white.png',repTea: 'Assam tea, Shou Mei tea, Bai Mu Dan tea, Bai Hao Yinzhen tea, Ceylon tea, Darjeeling white tea'}, 
{name: 'Green', title: 'greentitle.png',  image: 'green.png',repTea: 'Sencha, Pouchong, Gyokuro, Genmaicha, Assam tea, Hojicha, Green tea'},
{name: 'Yellow', title: 'yellowtitle.png',  image: 'yellow.png',repTea: 'Junshan Yinzhen tea, Huoshan Huangya tea'}])


Tea.create(name: 'Ban Tian Yao tea', tea_type_id: 2, region: 'Wuyi Mountains')
Tea.create(name: 'Darjeeling tea', tea_type_id: 1, region: 'Darjeeling')
Tea.create(name: 'Jin Fo tea', tea_type_id: 2, region: 'Wuyi Mountains')
Tea.create(name: 'Hojicha', tea_type_id: 4, region: 'Japan')
Tea.create(name: 'Lapsang souchong', tea_type_id: 1, region: 'Wuyi Mountains')
Tea.create(name: 'Chun Mee tea', tea_type_id: 4, region: 'Zhejiang')
Tea.create(name: 'Genmaicha', tea_type_id: 4, region: 'East Asia')
Tea.create(name: 'Qi Lan tea', tea_type_id: 2, region: 'Wuyi Mountains')
Tea.create(name: 'Kamairicha tea', tea_type_id: 4, region: 'Japan')
Tea.create(name: 'Da Fang tea', tea_type_id: 4, region: 'Anhui')
Tea.create(name: 'Bancha tea', tea_type_id: 4, region: 'Japan')
Tea.create(name: 'Huang Guanyin tea', tea_type_id: 2, region: 'Wuyi Mountains')
Tea.create(name: 'Hou Kui tea', tea_type_id: 4, region: 'Anhui')
Tea.create(name: 'Longjing', tea_type_id: 4, region: 'Zhejiang')
Tea.create(name: 'Rize Tea', tea_type_id: 1, region: 'Rize Province')
Tea.create(name: 'Shincha tea', tea_type_id: 4, region: 'Japan')
Tea.create(name: 'Keemun tea', tea_type_id: 1, region: 'Qimen County')
Tea.create(name: 'Pouchong', tea_type_id: 2, region: 'Fujian')
Tea.create(name: 'Tieguanyin', tea_type_id: 2, region: 'Anxi County')
Tea.create(name: 'Gunpowder tea', tea_type_id: 4, region: 'Zhejiang')
Tea.create(name: 'Bai Mu Dan tea', tea_type_id: 3, region: 'Fujian')
Tea.create(name: 'Jin Suo Chi tea', tea_type_id: 2, region: 'Wuyi Mountains')
Tea.create(name: 'Gyokuro', tea_type_id: 4, region: 'Japan')
Tea.create(name: 'Maccha', tea_type_id: 4, region: 'Japan')
Tea.create(name: 'Ceylon tea', tea_type_id: 1, region: 'Sri Lanka')
Tea.create(name: 'Kabusecha tea', tea_type_id: 4, region: 'Japan')
Tea.create(name: 'Shou Mei tea', tea_type_id: 3, region: 'China')
Tea.create(name: 'Mecha tea', tea_type_id: 4, region: 'Japan')
Tea.create(name: 'Ceylon tea', tea_type_id: 4, region: 'Uva Province')
Tea.create(name: 'Ceylon tea', tea_type_id: 3, region: 'Nuwara Eliya')
Tea.create(name: 'Nepal tea', tea_type_id: 1, region: 'Wuyi Nepal')
Tea.create(name: 'Nilgiri tea', tea_type_id: 1, region: 'The Nilgiris District')
Tea.create(name: 'Bai Ji Guan tea', tea_type_id: 2, region: 'Wuyi Mountains')
Tea.create(name: 'Huoshan Huangya tea', tea_type_id: 5, region: 'Anhui')
Tea.create(name: 'Bu Zhi Chun tea', tea_type_id: 2, region: 'Wuyi Mountains')
Tea.create(name: 'Dian Hong tea', tea_type_id: 1, region: 'Yunnan')
Tea.create(name: 'Hyson', tea_type_id: 4, region: 'China')
Tea.create(name: 'Da Hong Pao tea', tea_type_id: 2, region: 'Wuyi Mountains')
Tea.create(name: 'Sencha', tea_type_id: 4, region: 'Japan')
Tea.create(name: 'Ying De Hong', tea_type_id: 1, region: 'Guangdong Province')
Tea.create(name: 'Junshan Yinzhen tea', tea_type_id: 5, region: 'China')
Tea.create(name: 'Kukicha', tea_type_id: 4, region: 'Japan')
Tea.create(name: 'Huang Mei Gui tea', tea_type_id: 2, region: 'Wuyi Mountains')
Tea.create(name: 'Tieluohan tea', tea_type_id: 2, region: 'Wuyi Mountains')
Tea.create(name: 'Assam tea', tea_type_id: 4, region: 'Assam')
Tea.create(name: 'Dong Ding tea', tea_type_id: 2, region: 'Taiwan')
Tea.create(name: 'Fo Shou tea', tea_type_id: 2)
Tea.create(name: 'Rou Gui', tea_type_id: 2, region: 'Wuyi Mountains')
Tea.create(name: 'Bai Hao Yinzhen tea', tea_type_id: 3, region: 'Fujian')
Tea.create(name: 'Shui Hsien tea', tea_type_id: 2, region: 'Wuyi Mountains')
Tea.create(name: 'Darjeeling white tea', tea_type_id: 3, region: 'Darjeeling')
Tea.create(name: 'Mao Feng tea', tea_type_id: 4, region: 'Anhui')
Tea.create(name: 'Bi Luo Chun tea', tea_type_id: 4, region: 'Jiangsu')
Tea.create(name: 'Mao Jian tea', tea_type_id: 4, region: 'Henan')
Tea.create(name: 'Tamaryokucha', tea_type_id: 4, region: 'Japan')
Tea.create(name: 'Vietnamese lotus tea', tea_type_id: 3, region: 'Vietnam')
Tea.create(name: 'Dong Fang Mei Ren tea', tea_type_id: 2)
Tea.create(name: 'Green tea', tea_type_id: 4)
Tea.create(name: 'Earl Grey tea', tea_type_id: 1)
Tea.create(name: 'Orange Pekoe', tea_type_id: 1, region: 'Sri Lankas')