# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

types = TeaType.create([{name: 'Black', repTea:'Lapsang souchong, Keemun tea, Assam tea, Nilgiri tea, Rize Tea, Dian Hong tea'},
{name: 'Oolong', repTea: 'Pouchong, Tieguanyin, Rou Gui, Darjeeling tea, Dong Ding tea, Shui Hsien tea'},
{name: 'White', repTea: 'Assam tea, Shou Mei tea, Bai Mu Dan tea, Bai Hao Yinzhen tea, Ceylon tea, Darjeeling white tea'}, 
{name: 'Green', repTea: 'Sencha, Pouchong, Gyokuro, Genmaicha, Assam tea, Hojicha, Green tea'},
{name: 'Yellow', repTea: 'Junshan Yinzhen tea, Huoshan Huangya tea'}])


Tea.create(name: 'Ban Tian Yao tea', teaType: types.second, region: 'Wuyi Mountains', likes: 0)
Tea.create(name: 'Darjeeling tea', teaType: types.at(0), region: 'Darjeeling', likes: 0)
Tea.create(name: 'Jin Fo tea', teaType: types.at(1), region: 'Wuyi Mountains', likes: 0)
Tea.create(name: 'Hojicha', teaType: types.at(3), region: 'Japan', likes: 0)
Tea.create(name: 'Lapsang souchong', teaType: types.first, region: 'Wuyi Mountains', likes: 0)
Tea.create(name: 'Chun Mee tea', teaType: types.at(3), region: 'Zhejiang', likes: 0)
Tea.create(name: 'Genmaicha', teaType: types.at(3), region: 'East Asia', likes: 0)
Tea.create(name: 'Qi Lan tea', teaType: types.at(1), region: 'Wuyi Mountains', likes: 0)
Tea.create(name: 'Kamairicha tea', teaType: types.at(3), region: 'Japan', likes: 0)
Tea.create(name: 'Da Fang tea', teaType: types.at(3), region: 'Anhui', likes: 0)
Tea.create(name: 'Bancha tea', teaType: types.at(3), region: 'Japan', likes: 0)
Tea.create(name: 'Huang Guanyin tea', teaType: types.at(1), region: 'Wuyi Mountains', likes: 0)
Tea.create(name: 'Hou Kui tea', teaType: types.at(3), region: 'Anhui', likes: 0)
Tea.create(name: 'Longjing', teaType: types.at(3), region: 'Zhejiang', likes: 0)
Tea.create(name: 'Rize Tea', teaType: types.first, region: 'Rize Province', likes: 0)
Tea.create(name: 'Shincha tea', teaType: types.at(3), region: 'Japan', likes: 0)
Tea.create(name: 'Keemun tea', teaType: types.first, region: 'Qimen County', likes: 0)
Tea.create(name: 'Pouchong', teaType: types.at(1), region: 'Fujian', likes: 0)
Tea.create(name: 'Tieguanyin', teaType: types.at(1), region: 'Anxi County', likes: 0)
Tea.create(name: 'Gunpowder tea', teaType: types.at(3), region: 'Zhejiang', likes: 0)
Tea.create(name: 'Bai Mu Dan tea', teaType: types.at(2), region: 'Fujian', likes: 0)
Tea.create(name: 'Jin Suo Chi tea', teaType: types.at(1), region: 'Wuyi Mountains', likes: 0)
Tea.create(name: 'Gyokuro', teaType: types.at(3), region: 'Japan', likes: 0)
Tea.create(name: 'Maccha', teaType: types.at(3), region: 'Japan', likes: 0)
Tea.create(name: 'Ceylon tea', teaType: types.first, region: 'Sri Lanka', likes: 0)
Tea.create(name: 'Kabusecha tea', teaType: types.at(3), region: 'Japan', likes: 0)
Tea.create(name: 'Shou Mei tea', teaType: types.at(2), region: 'China', likes: 0)
Tea.create(name: 'Mecha tea', teaType: types.at(3), region: 'Japan', likes: 0)
Tea.create(name: 'Ceylon tea', teaType: types.at(3), region: 'Uva Province', likes: 0)
Tea.create(name: 'Ceylon tea', teaType: types.at(2), region: 'Nuwara Eliya', likes: 0)
Tea.create(name: 'Nepal tea', teaType: types.first, region: 'Wuyi Nepal', likes: 0)
Tea.create(name: 'Nilgiri tea', teaType: types.first, region: 'The Nilgiris District', likes: 0)
Tea.create(name: 'Bai Ji Guan tea', teaType: types.at(1), region: 'Wuyi Mountains', likes: 0)
Tea.create(name: 'Huoshan Huangya tea', teaType: types.at(4), region: 'Anhui', likes: 0)
Tea.create(name: 'Bu Zhi Chun tea', teaType: types.at(1), region: 'Wuyi Mountains', likes: 0)
Tea.create(name: 'Dian Hong tea', teaType: types.at(0), region: 'Yunnan', likes: 0)
Tea.create(name: 'Hyson', teaType: types.at(3), region: 'China', likes: 0)
Tea.create(name: 'Da Hong Pao tea', teaType: types.at(1), region: 'Wuyi Mountains', likes: 0)
Tea.create(name: 'Sencha', teaType: types.at(3), region: 'Japan', likes: 0)
Tea.create(name: 'Ying De Hong', teaType: types.at(0), region: 'Guangdong Province', likes: 0)
Tea.create(name: 'Junshan Yinzhen tea', teaType: types.at(4), region: 'China', likes: 0)
Tea.create(name: 'Kukicha', teaType: types.at(3), region: 'Japan', likes: 0)
Tea.create(name: 'Huang Mei Gui tea', teaType: types.at(1), region: 'Wuyi Mountains', likes: 0)
Tea.create(name: 'Tieluohan tea', teaType: types.at(1), region: 'Wuyi Mountains', likes: 0)
Tea.create(name: 'Assam tea', teaType: types.at(3), region: 'Assam', likes: 0)
Tea.create(name: 'Dong Ding tea', teaType: types.at(1), region: 'Taiwan', likes: 0)
Tea.create(name: 'Fo Shou tea', teaType: types.at(1), likes: 0)
Tea.create(name: 'Rou Gui', teaType: types.at(1), region: 'Wuyi Mountains', likes: 0)
Tea.create(name: 'Bai Hao Yinzhen tea', teaType: types.at(2), region: 'Fujian', likes: 0)
Tea.create(name: 'Shui Hsien tea', teaType: types.at(1), region: 'Wuyi Mountains', likes: 0)
Tea.create(name: 'Darjeeling white tea', teaType: types.at(2), region: 'Darjeeling', likes: 0)
Tea.create(name: 'Mao Feng tea', teaType: types.at(3), region: 'Anhui', likes: 0)
Tea.create(name: 'Bi Luo Chun tea', teaType: types.at(3), region: 'Jiangsu', likes: 0)
Tea.create(name: 'Mao Jian tea', teaType: types.at(3), region: 'Henan', likes: 0)
Tea.create(name: 'Tamaryokucha', teaType: types.at(3), region: 'Japan', likes: 0)
Tea.create(name: 'Vietnamese lotus tea', teaType: types.at(3), region: 'Vietnam', likes: 0)
Tea.create(name: 'Dong Fang Mei Ren tea', teaType: types.at(1), likes: 0)
Tea.create(name: 'Green tea', teaType: types.at(3), likes: 0)
Tea.create(name: 'Earl Grey tea', teaType: types.at(0), likes: 0)
Tea.create(name: 'Orange Pekoe', teaType: types.at(0), region: 'Sri Lankas', likes: 0)
